version: '2'
services:
  rtkbase:
    build: .
    image: rtkbase:1.0.0
    network_mode: host
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    volumes:
      - "/run/udev:/run/udev:ro"
    cap_add:
      - SYS_RAWIO
    restart: on-failure

