version: '2'
services:
  rtkbase:
    build: .
    image: rtkbase:1.0.0
    network_mode: host
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
    cap_add:
      - SYS_RAWIO
    restart: on-failure

